//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jumper.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public System.Guid Id { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public int Radius { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
